version: '3.9'
services:
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_DB=my_posts_database
      - POSTGRES_USER=facu
      - POSTGRES_PASSWORD=facu123
    ports:
      - 5432:5432
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@mail.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - 5050:80
    depends_on:
      - postgres
